# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(590, 229)
        self.gridLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(80, 40, 431, 171))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.czyPrawdilowaLabel = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.czyPrawdilowaLabel.setObjectName("czyPrawdilowaLabel")
        self.gridLayout.addWidget(self.czyPrawdilowaLabel, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.wynikLabel = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.wynikLabel.setText("")
        self.wynikLabel.setObjectName("wynikLabel")
        self.gridLayout.addWidget(self.wynikLabel, 2, 1, 1, 2)
        self.wagaBox = QtWidgets.QSpinBox(parent=self.gridLayoutWidget)
        self.wagaBox.setMaximum(999)
        self.wagaBox.setObjectName("wagaBox")
        self.gridLayout.addWidget(self.wagaBox, 0, 1, 1, 1)
        self.kobietaBox = QtWidgets.QRadioButton(parent=self.gridLayoutWidget)
        self.kobietaBox.setObjectName("kobietaBox")
        self.gridLayout.addWidget(self.kobietaBox, 3, 1, 1, 1)
        self.mezczyznaBox = QtWidgets.QRadioButton(parent=self.gridLayoutWidget)
        self.mezczyznaBox.setObjectName("mezczyznaBox")
        self.gridLayout.addWidget(self.mezczyznaBox, 3, 2, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.obliczButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.obliczButton.setObjectName("obliczButton")
        self.gridLayout.addWidget(self.obliczButton, 1, 1, 1, 2)
        self.wzrostBox = QtWidgets.QSpinBox(parent=self.gridLayoutWidget)
        self.wzrostBox.setMaximum(999)
        self.wzrostBox.setObjectName("wzrostBox")
        self.gridLayout.addWidget(self.wzrostBox, 0, 3, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "BMI Kalkulator"))
        self.czyPrawdilowaLabel.setText(_translate("Dialog", "Waga prawidłowa"))
        self.label_2.setText(_translate("Dialog", "Wzrost"))
        self.kobietaBox.setText(_translate("Dialog", "kobieta"))
        self.mezczyznaBox.setText(_translate("Dialog", "mezczyzna"))
        self.label.setText(_translate("Dialog", "Waga"))
        self.obliczButton.setText(_translate("Dialog", "Oblicz"))
